### PR TITLE
Fix: Spelling correction "targetting"

### LINKED ISSUE #267: docs: "targetting" typo
Spelling mistake for "targetting" in Readme, reference to: https://github.com/googleapis/google-cloud-node/issues/3019

Thanks.

### PR DESCRIPTION
**Pull request by jainsamyak**
Spelling correction for targetting to targeting

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-talent/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #267  🦕

### CODE REVIEW

**Comment by jainsamyak** [comment]
@googlebot I signed it!

**Review by JustinBeckwith — CHANGES_REQUESTED** [review]
Greetings, and thank you for the PR!  However, your README is in another castle.  This README is auto generated by a robot, which does some other templating tricks.  The source this is generated from lives here:
https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/node_library/README.md

Would you be willing to float a patch there?  Thank you so much!

**Comment by jainsamyak** [comment]
Hi Justin,
Thanks for the helpful tip! I'll open a patch for that file instead.

Thanks.

**Comment by bcoe** [comment]
@jainsamyak thank you for the patch 👌 this file is actually templated, if we fix the spelling mistake [here](https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/node_library/README.md) it will fix every one of our READMEs.

**Comment by jainsamyak** [comment]
> Greetings, and thank you for the PR! However, your README is in another castle. This README is auto generated by a robot, which does some other templating tricks. The source this is generated from lives here:
> https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/node_library/README.md
> 
> Would you be willing to float a patch there? Thank you so much!

I've created a pull request for the same here: https://github.com/googleapis/synthtool/pull/852
I think we can close this one?

**Pull request closed without merging**
